[tools]
python = { version = "sub-0.1:latest", virtualenv = ".venv" }
java = ["temurin-21", "temurin-8"]
node = "lts"
protoc = "latest"
ruby = "latest"
racket = "8.9"
zig = "latest"
go = "latest"

[plugins]
zig = "https://github.com/cheetah/asdf-zig.git"
racket = "https://github.com/MisLink/asdf-racket.git"
protoc = "https://github.com/paxosglobal/asdf-protoc.git"


[settings]
plugin_autoupdate_last_check_duration = "1 week"
experimental = true
env_file = ".env"

[settings.status]
missing_tools = false
