[tools]
python = ["latest", "sub-0.1:latest"]
java = ["temurin-21"]
node = "lts"
ruby = "latest"
zig = "latest"
go = ["latest", "sub-0.1:latest"]
"go:github.com/google/wire/cmd/wire" = "latest"
"pipx:black" = "latest"
"pipx:calibreweb" = "latest"
"pipx:ipython" = "latest"
"pipx:litecli" = "latest"
"pipx:mycli" = "latest"
"pipx:mypy" = "latest"
"pipx:pdm" = "latest"
"pipx:pgcli" = "latest"
"pipx:pre-commit" = "latest"
"pipx:ruff" = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-wizard" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:cargo-machete" = "latest"
"cargo:samply" = "latest"
"cargo:sqlx-cli" = "latest"
"cargo:trunk" = "latest"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "latest"
"go:golang.org/x/tools/cmd/gonew" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/googleapis/api-linter/cmd/api-linter" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:entgo.io/ent/cmd/ent" = "latest"
"go:github.com/yoheimuta/protolint/cmd/protolint" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"npm:eslint" = "latest"
"cargo:watchexec-cli" = "latest"
"pipx:tach" = "latest"
"go:github.com/cweill/gotests/gotests" = "latest"
"go:github.com/fatih/gomodifytags" = "latest"
"go:github.com/josharian/impl" = "latest"
"cargo:binocle" = "latest"
"go:github.com/Zxilly/go-size-analyzer/cmd/gsa" = "latest"
"go:capnproto.org/go/capnp/v3/capnpc-go" = "latest"
"go:github.com/moderato-app/live-pprof" = "v1"
"cargo:git-absorb" = "latest"
"cargo:bacon" = "latest"
"cargo:binsider" = { "version" = "latest", "default-features" = "false" }
"aqua:protocolbuffers/protobuf/protoc" = "latest"


[settings]
legacy_version_file = false
plugin_autoupdate_last_check_duration = "1 week"
experimental = true
python_compile = true

[settings.status]
missing_tools = "never"
show_env = true
