[tools]
python = "sub-0.1:latest"
java = "temurin-21"
node = "lts"
protoc = "latest"
ruby = "latest"
racket = "8"
zig = "latest"
go = ["latest", "prefix:1.21"]

[plugins]
zig = "https://github.com/cheetah/asdf-zig.git"
racket = "https://github.com/MisLink/asdf-racket.git"
protoc = "https://github.com/paxosglobal/asdf-protoc.git"


[settings]
plugin_autoupdate_last_check_duration = "1 week"
experimental = true

[settings.status]
missing_tools = false
show_env = true
