dir=${HOME}/Downloads
log=-
continue=true
max-connection-per-server=5
min-split-size=10M
split=10
enable-rpc=true
rpc-allow-origin-all=true
rpc-listen-all=true
rpc-secret=
disk-cache=20M
input-file=${HOME}/.aria2/aria2.session
save-session=${HOME}/.aria2/aria2.session
save-session-interval=60
