[tools]
python = "3.11"
java = "temurin-21.0.1+12.0.LTS"
node = "lts"
protoc = "latest"
ruby = "3.2"
racket = "8.9"
elixir = "1.15.7-otp-26"
zig = "0.11"
go = "1.21.4"

[settings]
plugin_autoupdate_last_check_duration = "1 week"
