# zsh
export PATH="$HOME/.local/bin:$PATH"
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="ys"
plugins=(npm docker docker-compose dotenv brew osx asdf git pip extract z zsh-syntax-highlighting zsh-completions zsh-autosuggestions)

. $ZSH/oh-my-zsh.sh

# export
export LC_ALL="en_US.UTF-8"
export EDITOR="vim"
export PIPENV_PYPI_MIRROR="https://pypi.tuna.tsinghua.edu.cn/simple"
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export PIPENV_VENV_IN_PROJECT=1

# source
if [[ -e ~/.alias ]]; then
    . ~/.alias
fi
