export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="ys"
DISABLE_AUTO_TITLE="true"
plugins=(git osx zsh-syntax-highlighting extract z safe-paste zsh-autosuggestions)
source $ZSH/oh-my-zsh.sh
export EDITOR='vim'

if [[ -e ~/.alias ]]; then
    source ~/.alias
fi

if [[ -e `pwd`/venv/bin/activate ]]; then
    source `pwd`/venv/bin/activate
elif [[ -e `pwd`/env/bin/activate ]]; then
    source `pwd`/venv/bin/activate
fi
