export PATH="$HOME/.local/bin:$PATH"
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="ys"
plugins=(npm docker docker-compose httpie dotenv brew osx asdf git pip extract z zsh-syntax-highlighting zsh-completions zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

export LC_ALL="en_US.UTF-8"
export EDITOR="vim"
export PIPENV_PYPI_MIRROR="https://pypi.tuna.tsinghua.edu.cn/simple"
export PIPENV_VENV_IN_PROJECT=1


if [[ -e ~/.alias ]]; then
    source ~/.alias
fi

if [[ -e `pwd`/venv/bin/activate ]]; then
    source `pwd`/venv/bin/activate
elif [[ -e `pwd`/.venv/bin/activate ]]; then
    source `pwd`/.venv/bin/activate
elif pipenv --venv &>/dev/null; then
    source `pipenv --venv`/bin/activate
fi

eval "$(pipenv --completion)"
